import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import { SidebarProvider } from "@/components/providers/SidebarProviders";
import AppLayout from "@/components/organisms/layouts/AppLayout";

const fontInter = {
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${fontInter.variable} overflow-x-hidden bg-background `}>
        <Providers>
          <SidebarProvider>
            <AppLayout>{children}</AppLayout>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
